// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2811.BunnyBot2013;

import org.usfirst.frc2811.BunnyBot2013.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    
    public JoystickButton shootButton;
    public JoystickButton changeTarget;
    public Joystick joystick;
    public static JoystickButton shiftButton;
    public static int FORE_BACK_STICK;//joystick for controlling robot in freedom
    public static final int FORE_BACK_STICK_CONTROLLER = 3;
    public static final int FORE_BACK_STICK_JOYSTICK = 1;
    public static int LEFT_RIGHT_STICK;
    public static boolean FORE_BACK_DIRECTION;//reverses direction of the stick
    public static boolean LEFT_RIGHT_DIRECTION;
    public static JoystickButton BallAdvanceButton;
    public static JoystickButton BallReverseButton;
    public static JoystickButton grabberToggle;
    
    public static Joystick joystick2;//hopefully robots quit
    public static JoystickButton turretLeft;
    public static JoystickButton turretRight;
    public static JoystickButton overVoltShooter;
    public static JoystickButton reverseShooter;
    
    public static JoystickButton toggleForeBackStick;
    
   
    public OI() {

        joystick = new Joystick(1);
               
        shiftButton = new JoystickButton(joystick,2);
        grabberToggle = new JoystickButton(joystick, 6);
        toggleForeBackStick = new JoystickButton(joystick,10);
        
        
        joystick2 = new Joystick(2);
        
       // shootButton = new JoystickButton(joystick,1);
        
        turretLeft = new JoystickButton(joystick2,4);
        turretRight = new JoystickButton(joystick2,5);
        
        BallAdvanceButton = new JoystickButton(joystick2,1);//may be joystick 2 b/c gunner
        BallReverseButton = new JoystickButton(joystick2,2);
        overVoltShooter = new JoystickButton(joystick2,3);
        reverseShooter = new JoystickButton(joystick2,7);
//            _____                    _____
//           |  7  |                  |  8  |
//           |_____|                  |_____|
//         __|__5__|_                _|__6__|__
//        |  / | \   \______________/          |
//        | |--+--|<--can't be used sorry 4    |
//        |  \ | /      9       10      1   3  |
//        |                               2    |
//       /      ___    nope            ___      \
//      /      / 3 \                  / 1 \      \
//     |      |4 + 4|________________|2 + 2|      |
//     |       \_3_/                  \_1_/       |
//     |       /                          \       |
//      \_____/                            \_____/
        
        shiftButton.whenPressed(new ShiftToggle());
        grabberToggle.whenPressed(new grabberToggle());
        toggleForeBackStick.whenPressed(new AxisToggle());
        
        FORE_BACK_STICK = 3;//2
        LEFT_RIGHT_STICK = 2;//3
        FORE_BACK_DIRECTION = false;//false
        LEFT_RIGHT_DIRECTION = false;//false

	    
        // SmartDashboard Buttons
       // SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

      //  SmartDashboard.putData("SetBallSpeed", new SetBallSpeed());

    }
    
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick() {
        return joystick;
    }
    public Joystick getJoystick2() {
        return joystick2;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

