// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2811.BunnyBot2013;

import org.usfirst.frc2811.BunnyBot2013.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    
    public JoystickButton fireButton;
    public JoystickButton changeTarget;
    public Joystick joystick;
    public static JoystickButton shiftButton;
    public static int FORE_BACK_STICK;//joystick for controlling robot in freedom
    public static int LEFT_RIGHT_STICK;
    public static boolean FORE_BACK_DIRECTION;//reverses direction of the stick
    public static boolean LEFT_RIGHT_DIRECTION;
    public static JoystickButton BallAdvanceButton;
    public static JoystickButton BallReverseButton;
    public static JoystickButton grabberToggle;
    
   // public static Joystick secondJoystick;
    
   
    public OI() {

        joystick = new Joystick(1);
        
        
        shiftButton = new JoystickButton(joystick,3);
        grabberToggle = new JoystickButton(joystick, 5);
        BallAdvanceButton = new JoystickButton(joystick,6);
        BallReverseButton = new JoystickButton(joystick,8);
        
     //   fireButton = new JoystickButton(secondJoystick, 1);
     //   changeTarget = new JoystickButton(secondJoystick, 2);
        
//            _____                    _____
//           |  7  |                  |  8  |
//           |_____|                  |_____|
//           |__5__|                  |__6__|
//         __________                __________
//        |  / | \   \______________/          |
//        | |--+--|<--can't be used sorry 4    |
//        |  \ | /      9       10      1   3  |
//        |                               2    |
//       /      ___                    ___      \
//      /      / 3 \                  / 1 \      \
//     |      |4 + 4|________________|2 + 2|      |
//     |       \_3_/                  \_1_/       |
//     |       /                          \       |
//      \_____/                            \_____/
//        
        
//        changeTarget.whenPressed(new TargetChanger());
       // fireButton.whenPressed(new FireBall());
        shiftButton.whenPressed(new ShiftToggle());
        grabberToggle.whenPressed(new grabberToggle());
        
        FORE_BACK_STICK = 3;//2
        LEFT_RIGHT_STICK = 2;//3
        FORE_BACK_DIRECTION = false;//false
        LEFT_RIGHT_DIRECTION = false;//false

	    
        // SmartDashboard Buttons
       // SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

      //  SmartDashboard.putData("SetBallSpeed", new SetBallSpeed());

    }
    
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick() {
        return joystick;
    }
  //  public Joystick getJoystick2() {
  //      return secondJoystick;
 //   }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

