// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2811.BunnyBot2013.subsystems;

//import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc2811.BunnyBot2013.RobotMap;

/**
 *
 */
public class BallShooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
        SpeedController shooterSpeedMotor = RobotMap.ballShooterShooterSpeedMotor;
        Encoder shooterSpeedSensor = RobotMap.ballShooterShooterSpeedSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

   

    protected void initDefaultCommand() {
        
        
    }
    public void setShooterSpeed(double input){
        shooterSpeedMotor.set(input);
    }
     // Initialize your subsystem here
//    public BallShooter() {
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
//        super("BallShooter", 1.0, 0.0, 0.0);
//        setAbsoluteTolerance(0.2);
//        getPIDController().setContinuous(false);
//        LiveWindow.addActuator("BallShooter", "PIDSubsystem Controller", getPIDController());
//        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
//
//        // Use these to get going:
//        // setSetpoint() -  Sets where the PID controller should move the system
//        //                  to
//        // enable() - Enables the PID controller.
//    }
//    
//    public void initDefaultCommand() {
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
//        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
//    
//        // Set the default command for a subsystem here.
//        //setDefaultCommand(new MySpecialCommand());
//    }
//    
//    protected double returnPIDInput() {
//        // Return your input value for the PID loop
//        // e.g. a sensor, like a potentiometer:
//        // yourPot.getAverageVoltage() / kYourMaxVoltage;
//	
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
//        return shooterSpeedSensor.pidGet();
//        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
//    }
//    
//    protected void usePIDOutput(double output) {
//        // Use output to drive your system, like a motor
//        // e.g. yourMotor.set(output);
//	
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
//     //   shooterSpeedMotor.pidWrite(output);
//        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
//    }
}
