// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2811.BunnyBot2013.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2811.BunnyBot2013.Robot;
import org.usfirst.frc2811.BunnyBot2013.RobotMap;

/**
 *
 */
public class FireBall extends CommandGroup {
    public int ballTime;
    public double fireTime;
    
    // Called just before this Command runs the first time
    protected void initialize() {
        RobotMap.ballManagerIntakeMotor.set(1);
        ballTime = 1;
        int ballcount = Robot.ballManager.decrementInternalCountDown();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        
        fireTime = Robot.timer.get();
        if(fireTime>=ballTime){
            RobotMap.ballManagerIntakeMotor.set(0);
            
        }         
        // turn on belt thingy
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if(fireTime>=ballTime){
            return true;
        }
        else{
            return false;  
        }
                
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }

    
    public  FireBall() {
           
        
    }
}
